- name: 'apt package installs'
  apt:
    pkg:
    - python3
    - python3-pip
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common
    - apt-transport-https
    state: latest
    update_cache: true

- name: 'add GPG key'
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: 'Add repo'
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable"
    state: present

- name: 'update repo'
  apt:
    upgrade: dist

- name: 'install docker'
  apt:
    pkg:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    state: latest
    update_cache: true

- name: 'Install docker-py'
  pip:
    name: docker-py
